import { chromium, expect } from '@playwright/test';
import { GifReader } from 'omggif';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const studio = page.getByRole('region', { name: 'GIF studio', exact: true });
async function download(link) {
  const event = page.waitForEvent('download'); await link.click();
  const file = await event;
  const stream = await file.createReadStream();
  const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  return Buffer.concat(chunks);
}
async function verifyGif(link) {
  const bytes = await download(link);
  expect(bytes.subarray(0, 6).toString()).toBe('GIF89a');
  const gif = new GifReader(bytes);
  expect(gif.width).toBe(320); expect(gif.height).toBe(320); expect(gif.numFrames()).toBe(20);
  expect(gif.loopCount()).toBe(0); expect(gif.frameInfo(0).delay).toBe(10);
  const a = Buffer.alloc(320 * 320 * 4); const b = Buffer.alloc(a.length);
  gif.decodeAndBlitFrameRGBA(0, a); gif.decodeAndBlitFrameRGBA(7, b);
  let changed = 0;
  for (let i = 0; i < a.length; i += 4) if (a[i] !== b[i] || a[i + 1] !== b[i + 1] || a[i + 2] !== b[i + 2]) changed++;
  expect(changed).toBeGreaterThan(500);
  expect(new Set(a).size).toBeGreaterThan(20);
  return bytes;
}
async function render() {
  await studio.getByRole('button', { name: 'Render GIF', exact: true }).click();
  await expect(studio.getByRole('status')).toContainText('GIF ready', { timeout: 90000 });
  await expect(studio.getByAltText('Rendered GIF preview')).toBeVisible();
  await expect.poll(() => studio.getByAltText('Rendered GIF preview').evaluate(img => img.complete && img.naturalWidth === 320)).toBe(true);
}
try {
  await page.goto('http://127.0.0.1:8787');
  await mkdir('test-results', { recursive: true });
  await page.screenshot({ path: 'test-results/10-workbench-before.png' });
  await page.getByRole('button', { name: 'GIF studio', exact: true }).click();
  await expect(studio.getByRole('button', { name: 'Render GIF', exact: true })).toBeDisabled();
  const fixture = (title, x, y, z) => ({ name: `${title}.json`, mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({
    hardware_ir_version: '0.2', overview: { title }, mechanical: { render_dimensions: { x_mm: x, y_mm: y, z_mm: z } },
  })) });
  await page.locator('input[type=file]').setInputFiles([fixture('Review workbench', 1800, 800, 900), fixture('Outside fixture', 400, 400, 400)]);
  await expect(page.locator('.asset')).toHaveCount(2);
  await studio.getByLabel('GIF resolution').selectOption('320');
  await studio.getByLabel('Duration').selectOption('2');
  await studio.getByLabel('Export scope').selectOption('section');
  await studio.getByLabel('Section width').fill('20');
  await studio.getByRole('button', { name: 'Render GIF', exact: true }).click();
  await expect(studio.getByRole('alert')).toContainText('must fit inside');
  await studio.getByLabel('Section width').fill('2');
  await render();
  await verifyGif(studio.getByRole('link', { name: 'Download GIF', exact: true }));
  const metadata = JSON.parse((await download(studio.getByRole('link', { name: 'Download review metadata' }))).toString());
  expect(metadata.scope).toBe('section'); expect(metadata.units).toBe('m');
  expect(metadata.assets.map(a => a.name)).toEqual(['Review workbench']);
  expect(metadata.region).toEqual({ x: 0, z: 0, width: 2, depth: 2 });
  await page.screenshot({ path: 'test-results/10-section-gif-after.png' });
  console.log('PASS section clipping/filter metadata, GIF dimensions, 20 decoded moving frames, looping and timing.');
  await studio.getByLabel('Export scope').selectOption('room');
  await render();
  const roomMetadata = JSON.parse((await download(studio.getByRole('link', { name: 'Download review metadata' }))).toString());
  expect(roomMetadata.assets).toHaveLength(2);
  await verifyGif(studio.getByRole('link', { name: 'Download GIF', exact: true }));
  console.log('PASS whole-room GIF with both assets.');
  await studio.getByLabel('Export scope').selectOption('asset');
  await studio.getByLabel('Preview motion').selectOption('sample');
  await render();
  await verifyGif(studio.getByRole('link', { name: 'Download GIF', exact: true }));
  const sampleMetadata = JSON.parse((await download(studio.getByRole('link', { name: 'Download review metadata' }))).toString());
  expect(sampleMetadata.assets).toHaveLength(1); expect(sampleMetadata.motion).toBe('sample');
  console.log('PASS selected-asset synthetic animation.');
  await studio.getByRole('button', { name: /Asset library/ }).click();
  await studio.getByRole('button', { name: 'Save selected asset to library' }).click();
  const card = studio.getByRole('article', { name: 'Review workbench', exact: true });
  await expect(card).toBeVisible();
  await studio.getByRole('button', { name: 'Save selected asset to library' }).click();
  await expect(studio.getByRole('article')).toHaveCount(1);
  await card.getByRole('button', { name: 'Render turntable' }).click();
  await expect(studio.getByRole('status')).toContainText('preview saved', { timeout: 90000 });
  await verifyGif(card.getByRole('link', { name: 'Download preview' }));
  await card.getByRole('button', { name: 'Render sample motion' }).click();
  await expect(studio.getByRole('status')).toContainText('preview saved', { timeout: 90000 });
  await verifyGif(card.getByRole('link', { name: 'Download preview' }));
  await page.screenshot({ path: 'test-results/10-library-after.png' });
  await page.reload();
  await page.getByRole('button', { name: 'GIF studio', exact: true }).click();
  await studio.getByRole('button', { name: /Asset library/ }).click();
  await expect(card).toBeVisible();
  await expect.poll(() => card.locator('img').evaluate(img => img.complete && img.naturalWidth === 320)).toBe(true);
  const savedMetadata = JSON.parse((await download(card.getByRole('link', { name: 'Preview metadata' }))).toString());
  expect(savedMetadata.motion).toBe('sample');
  await card.getByRole('button', { name: 'Add to room' }).click();
  await expect(page.locator('.asset')).toHaveCount(1);
  console.log('PASS deduplicated persistent library, both preview presets, GIF recovery after reload and add-to-room.');
  await studio.getByRole('button', { name: 'Floor export', exact: true }).click();
  await studio.getByLabel('GIF resolution').selectOption('640');
  await studio.getByLabel('Duration').selectOption('4');
  await studio.getByRole('button', { name: 'Render GIF', exact: true }).click();
  await studio.getByRole('button', { name: 'Cancel export' }).click();
  await expect(studio.getByRole('status')).toContainText('cancelled');
  await page.getByRole('button', { name: 'Enter fullscreen' }).click();
  await expect(studio).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.fullscreenElement.contains(document.querySelector('.capture-panel')))).toBe(true);
  await page.screenshot({ path: 'test-results/10-fullscreen-after.png' });
  await page.getByRole('button', { name: 'Exit fullscreen' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(studio).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/10-mobile-after.png', fullPage: true });
  await studio.getByRole('button', { name: /Asset library/ }).click();
  await card.getByRole('button', { name: 'Remove from library' }).click();
  await expect(studio.getByRole('article')).toHaveCount(0);
  await expect(page.locator('.asset')).toHaveCount(1);
  expect(errors).toEqual([]);
  console.log('PASS cancellation, fullscreen tools, mobile layout, and library deletion retaining the room asset. Zero page errors.');
} finally { await browser.close(); }
